In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('laptop_details.xlsx')
data.shape

(300, 17)

In [4]:
data.drop('Company',axis=1,inplace=True)
data.drop('ThirdPL',axis=1,inplace=True)
data.drop('Abbreviation',axis=1,inplace=True)
data.drop('Weight',axis=1,inplace=True)

In [5]:
data['sales_location']=data['Sales_location']
data.drop('Sales_location',axis=1,inplace=True)

In [6]:
data.Price_euros=data.Price_euros.astype(float)

In [7]:
data.head()

Product TypeName  Inches             ScreenResolution  \
0  Alienware 15   Gaming    15.6            Full HD 1920x1080   
1  Alienware 15   Gaming    15.6            Full HD 1920x1080   
2  Alienware 15   Gaming    15.6            Full HD 1920x1080   
3  Alienware 15   Gaming    15.6        4K Ultra HD 3840x2160   
4  Alienware 17   Gaming    17.3  IPS Panel Full HD 1920x1080   

                           Cpu   Ram                Memory  \
0  Intel Core i5 7300HQ 2.5GHz  16GB  128GB SSD +  1TB HDD   
1  Intel Core i7 7820HK 2.9GHz  16GB  256GB SSD +  1TB HDD   
2  Intel Core i7 7700HQ 2.8GHz  16GB  256GB SSD +  1TB HDD   
3  Intel Core i7 6700HQ 2.6GHz  16GB  256GB SSD +  1TB HDD   
4  Intel Core i7 7700HQ 2.8GHz  16GB  256GB SSD +  1TB HDD   

                       Gpu       OpSys  Price_euros Stock_in_date    Status  \
0  Nvidia GeForce GTX 1060  Windows 10      2051.00    2018-07-19      sold   
1  Nvidia GeForce GTX 1070  Windows 10      2813.75    2018-09-10      sold   
2  Nvidia GeForce GTX 1070  Windows 10      2774.63    2018-10-01  not sold   
3  Nvidia GeForce GTX 970M  Windows 10      1329.00    2018-08-12      sold   
4  Nvidia GeForce GTX 1060  Windows 10      2456.34    2018-08-24      sold   

  sales_location  
0      New Delhi  
1    West Bengal  
2    Maharashtra  
3      New Delhi  
4         Odisha

In [8]:
train_data=data[data.Status=="sold"]
test_data=data[data.Status=="not sold"]

In [9]:
stock_in_date=test_data.Stock_in_date

In [10]:
product=test_data.Product

In [11]:
train_data.shape

(188, 13)

In [12]:
test_data.shape

(112, 13)

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le=LabelEncoder()
for i in([0,1,2,3,4,5,6,7,8]):
    array=le.fit_transform(np.array(train_data.iloc[:,i]))
    train_data.iloc[:,i]=array

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [15]:
for i in([0,1,2,3,4,5,6,7,8]):
    array=le.fit_transform(np.array(test_data.iloc[:,i]))
    test_data.iloc[:,i]=array

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [16]:
test_data.head()

Product  TypeName  Inches  ScreenResolution  Cpu  Ram  Memory  Gpu  OpSys  \
2         0         1       5                 6   19    0       6   21      1   
7         1         1       6                10   19    0       1   21      1   
15        1         1       6                 2   15    0      10   22      1   
18        1         1       6                 6   14    2       6   21      1   
22        2         0       0                13   25    3       8    7      1   

    Price_euros Stock_in_date    Status sales_location  
2       2774.63    2018-10-01  not sold    Maharashtra  
7       3012.77    2018-10-15  not sold        Gujarat  
15      2758.00    2018-07-11  not sold    Maharashtra  
18      2800.00    2018-10-01  not sold        Gujarat  
22       479.00    2018-10-12  not sold      Rajasthan

In [17]:
train_data.head()

Product  TypeName  Inches  ScreenResolution  Cpu  Ram  Memory  Gpu  OpSys  \
0        0         2       4                 5   15    1       2   27      2   
1        0         2       4                 5   30    1       9   28      2   
3        0         2       4                 3   22    1       9   31      2   
4        1         2       5                 9   29    1       9   27      2   
5        1         2       5                 6   30    1       9   28      2   

   Price_euros Stock_in_date Status sales_location  
0      2051.00    2018-07-19   sold      New Delhi  
1      2813.75    2018-09-10   sold    West Bengal  
3      1329.00    2018-08-12   sold      New Delhi  
4      2456.34    2018-08-24   sold         Odisha  
5      2799.00    2018-10-15   sold     Tamil Nadu

In [18]:
train_data.iloc[:,11] = train_data.iloc[:,11].map({'sold': 1, 'not sold': 0})
test_data.iloc[:,11] = test_data.iloc[:,11].map({'sold': 1, 'not sold': 0})

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [19]:
train_data.head()

Product  TypeName  Inches  ScreenResolution  Cpu  Ram  Memory  Gpu  OpSys  \
0        0         2       4                 5   15    1       2   27      2   
1        0         2       4                 5   30    1       9   28      2   
3        0         2       4                 3   22    1       9   31      2   
4        1         2       5                 9   29    1       9   27      2   
5        1         2       5                 6   30    1       9   28      2   

   Price_euros Stock_in_date  Status sales_location  
0      2051.00    2018-07-19       1      New Delhi  
1      2813.75    2018-09-10       1    West Bengal  
3      1329.00    2018-08-12       1      New Delhi  
4      2456.34    2018-08-24       1         Odisha  
5      2799.00    2018-10-15       1     Tamil Nadu

In [20]:
X_train=train_data.iloc[:,:-1]
Y_train=train_data.iloc[:,-1]
X_test=test_data.iloc[:,:-1]
Y_test=test_data.iloc[:,-1]

In [21]:
array=le.fit_transform(np.array(Y_train))
Y_train=array
array=le.fit_transform(np.array(Y_test))
Y_test=array

In [22]:
Y_test

array([ 5,  1,  5,  1,  9,  1,  3,  6,  6, 10,  4, 10,  5, 10,  4,  2,  0,
        0,  9,  0,  0,  4,  8, 12, 12,  5,  4,  8,  7, 11, 12,  5,  1,  0,
       12, 10, 12,  7,  4,  5,  0, 11,  5,  8,  5,  4, 11,  8, 11,  0, 10,
        5,  7,  1, 11,  5,  7,  9, 12,  0, 11,  7,  1,  4,  2,  1, 10,  7,
        1,  9, 11,  1,  5,  5,  5, 10, 10, 12,  1,  4, 10, 11, 10,  5,  9,
        5,  0,  9,  4,  9, 12, 12,  2, 12,  1,  1,  0,  4,  1,  9,  5,  9,
        2,  8,  4,  0,  2,  4,  9,  5, 12,  5], dtype=int64)

In [23]:
X_train.shape

(188, 12)

In [24]:
X_test.shape

(112, 12)

In [25]:
stock_in_date = X_test['Stock_in_date']
X_train.drop('Stock_in_date',axis=1,inplace=True)
X_test.drop('Stock_in_date',axis=1,inplace=True)
stock_in_date

2     2018-10-01
7     2018-10-15
15    2018-07-11
18    2018-10-01
22    2018-10-12
23    2018-09-10
28    2018-10-27
29    2018-09-22
31    2018-09-11
33    2018-08-27
38    2018-07-24
39    2018-08-07
41    2018-09-06
46    2018-08-23
47    2018-09-10
50    2018-09-02
53    2018-09-25
57    2018-10-05
59    2018-08-15
63    2018-10-10
66    2018-10-11
72    2018-05-26
73    2018-06-15
76    2018-09-04
80    2018-09-18
84    2018-08-24
87    2018-11-09
88    2018-10-22
92    2018-10-26
94    2018-07-10
         ...    
226   2018-10-28
228   2018-09-20
231   2018-08-19
233   2018-07-24
234   2018-07-18
243   2018-10-11
244   2018-09-21
246   2018-06-18
250   2018-09-04
256   2018-10-16
257   2018-10-07
260   2018-06-18
263   2018-06-28
264   2018-10-10
266   2018-07-27
267   2018-06-16
268   2018-08-16
270   2018-09-20
272   2018-11-06
274   2018-09-01
277   2018-08-21
281   2018-10-14
283   2018-07-01
284   2018-10-29
286   2018-08-11
289   2018-06-10
291   2018-07-28
294   2018-05-

In [26]:
X_train.shape

(188, 11)

In [27]:
X_test.shape

(112, 11)

In [28]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [29]:
X_train

array([[-1.3522906 , -0.99689442,  0.36372915, ...,  0.24856253,
         1.14140802,  0.        ],
       [-1.3522906 , -0.99689442,  0.36372915, ...,  0.24856253,
         2.21052297,  0.        ],
       [-1.3522906 , -0.99689442,  0.36372915, ...,  0.24856253,
         0.12941065,  0.        ],
       ...,
       [ 1.5753087 ,  0.30914148,  0.36372915, ...,  0.24856253,
         0.81762492,  0.        ],
       [ 1.5753087 ,  0.30914148,  0.36372915, ...,  0.24856253,
         1.62918514,  0.        ],
       [ 1.5753087 ,  0.30914148,  0.36372915, ...,  0.24856253,
         1.42129117,  0.        ]])

In [30]:
X_test

array([[-1.3522906 , -1.64991237,  1.31346639, ..., -2.21089828,
         2.15569009, -1.        ],
       [-1.30001204, -1.64991237,  2.26320363, ..., -2.21089828,
         2.48948102, -1.        ],
       [-1.30001204, -1.64991237,  2.26320363, ..., -2.21089828,
         2.13238051, -1.        ],
       ...,
       [ 0.73885176, -0.99689442,  1.31346639, ..., -2.21089828,
         0.92835594, -1.        ],
       [ 0.73885176, -0.99689442,  1.31346639, ..., -2.21089828,
         0.71810718, -1.        ],
       [ 0.79113032, -0.34387647,  1.31346639, ..., -2.21089828,
         0.69043844, -1.        ]])

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
clf1=RandomForestClassifier()
clf1.fit(X_train,Y_train)
Y_pred=clf1.predict(X_test)

In [32]:
clf1.score(X_test,Y_test)

0.08928571428571429

In [33]:
X_test.shape

(112, 11)

In [34]:
from sklearn.svm import SVC
clf2=SVC()
clf2.fit(X_train, Y_train)
Y_pred=clf1.predict(X_test)
clf2.score(X_test,Y_test)

0.017857142857142856

In [35]:
from sklearn.neighbors import KNeighborsClassifier  
clf3=KNeighborsClassifier(n_neighbors=5)  
clf3.fit(X_train,Y_train)
Y_pred=clf3.predict(X_test)
clf3.score(X_test,Y_test)

0.05357142857142857

In [36]:
quantity=np.random.random_integers(5,high=15,size=(X_test.shape[0],))
quantity

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(5, 15 + 1) instead
  """Entry point for launching an IPython kernel.


array([12, 11, 14, 14, 11, 11,  5, 15, 14,  5,  8,  5, 11,  8,  5,  9, 10,
        9,  6,  7,  7,  7,  8, 11, 13, 13, 14,  9,  7,  5, 12,  7,  9, 15,
       14, 14, 10,  7,  7,  6,  5, 14, 12,  8,  8, 12, 14,  7,  6, 12, 11,
       11,  9,  8,  5,  5, 11,  9, 11, 12, 11,  6,  7, 14,  5, 12, 15,  9,
        9, 12, 12, 12, 11,  6,  5, 15,  5,  7, 14,  6, 15, 13,  9, 14, 11,
        9, 10, 13, 10,  5,  7, 11, 10,  9,  7,  5,  5, 12, 15, 15, 12,  6,
       10, 15, 10, 15, 15,  6, 11, 14, 12, 14])

In [37]:
prediction=pd.DataFrame(product,columns=['Product'])
prediction['Quantity']=quantity
prediction['Stock_in_date']=stock_in_date
prediction['Location']=le.inverse_transform(Y_pred)
prediction.head()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Product  Quantity Stock_in_date        Location
2    Alienware 15        12    2018-10-01  Andhra Pradesh
7    Alienware 17        11    2018-10-15      Maharshtra
15   Alienware 17        14    2018-07-11         Gujarat
18   Alienware 17        14    2018-10-01  Andhra Pradesh
22  Inspiron 3168        11    2018-10-12      Tamil Nadu

In [38]:
prediction.to_csv('Result.csv')